name: Build & Publish (main)
on:
  push:
    branches: [ main ]

    paths-ignore:
      - ".github/**"
      - "README**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup ENV
      run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Setup Docker Build X
      uses: docker/setup-buildx-action@v2
    - name: Log into container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
    - name: Build Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{ github.ref_name }}-SNAPSHOT
          COMMIT_SHA=${{ env.GITHUB_SHA_SHORT }}
